# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            DL/ML Notes
tagline:          'A Jekyll theme'
description:      '좋은 글을 모으고 좋은 글을 씁시다'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Deep Insiders'
  # url:            deep-insiders.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

---
layout: page
title: About
---